"""CIM Module 5 — CFO portfolio narrative generator (Section 6.8).

Produces the monthly CFO credit narrative as a structured Markdown
document (delivered via email; no bespoke frontend — see FOR IT MANAGERS,
Chapter 6). Numbers come from the CIM modules; the LLM only drafts prose
around them and never generates figures itself (PRA SS1/23 boundary).
"""
from __future__ import annotations

import datetime as dt
from dataclasses import dataclass


@dataclass(frozen=True)
class PortfolioSnapshot:
    reporting_date: dt.date
    total_exposure_gbp: float
    weighted_avg_pd: float
    watchlist_count: int
    covenant_breaches: int
    ews_alerts: int


def build_narrative(snap: PortfolioSnapshot, prior: PortfolioSnapshot) -> str:
    """Assemble the CFO narrative. All figures are computed inputs."""
    pd_delta_bps = (snap.weighted_avg_pd - prior.weighted_avg_pd) * 1e4
    direction = "deteriorated" if pd_delta_bps > 0 else "improved"
    return "\n".join([
        f"# AWB Corporate Credit — CFO Narrative ({snap.reporting_date:%B %Y})",
        "",
        "## Headline",
        f"Total corporate exposure £{snap.total_exposure_gbp/1e9:.1f}B. "
        f"Portfolio weighted-average PD {snap.weighted_avg_pd:.2%}, "
        f"{direction} {abs(pd_delta_bps):.0f}bps month-on-month.",
        "",
        "## Watchlist and Early Warning",
        f"{snap.watchlist_count} names on watch "
        f"({snap.ews_alerts} new EWS alerts this month).",
        "",
        "## Covenant Compliance",
        f"{snap.covenant_breaches} covenant breach(es) under amended terms; "
        "all tested against latest facility letters (Section 6.3).",
        "",
        "_Generated by CIM MR-2026-055. Figures are model outputs; "
        "narrative drafted by the reporting LLM and reviewed before release._",
    ])


if __name__ == "__main__":
    prior = PortfolioSnapshot(dt.date(2026, 5, 31), 12.4e9, 0.0181, 14, 1, 3)
    now = PortfolioSnapshot(dt.date(2026, 6, 30), 12.6e9, 0.0176, 12, 1, 2)
    print(build_narrative(now, prior))
