"""LLM-assisted leverage ratio variance commentary.

Model ID: MR-2026-071 | LLM: Gemini 3.5 Flash
Trigger: leverage ratio moves >50bps quarter-on-quarter.
Output: AI-ASSISTED DRAFT; CFO review mandatory before board.
"""
from __future__ import annotations
from dataclasses import dataclass
from decimal import Decimal
from typing import Optional
import logging
import os

import google.generativeai as genai

from awb_commons.models import LeverageRatioResult

log = logging.getLogger(__name__)
TRIGGER_BPS = 50


@dataclass
class LeverageCommentary:
    """CFO-ready leverage ratio commentary."""
    current_quarter: str
    prior_ratio_pct: float
    current_ratio_pct: float
    change_bps: float
    commentary_text: str
    requires_cfo_approval: bool = True
    generated_by: str = "Gemini 3.5 Flash (AI-ASSISTED)"


class LeverageRatioCommentaryGenerator:
    """Generate CFO commentary when leverage ratio moves >50bps.

    Uses Gemini 3.5 Flash to produce a 250-word board-ready
    commentary explaining the movement by component driver.
    CFO review gate is mandatory — never auto-publish.

    Args:
        model_id: Registered model ID (MR-2026-071).
    """

    def __init__(
        self,
        model_id: str = "MR-2026-071",
    ) -> None:
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GEMINI_API_KEY required")
        genai.configure(api_key=api_key)
        self._model = genai.GenerativeModel("gemini-3.5-flash")
        self._model_id = model_id

    def generate_variance_commentary(
        self,
        prior: LeverageRatioResult,
        current: LeverageRatioResult,
    ) -> Optional[LeverageCommentary]:
        """Generate commentary if movement exceeds 50bps.

        Args:
            prior: Prior quarter leverage ratio result.
            current: Current quarter leverage ratio result.

        Returns:
            LeverageCommentary or None if change < 50bps.
        """
        change_bps = (
            (current.leverage_ratio_pct - prior.leverage_ratio_pct)
            * 100
        )
        if abs(change_bps) < TRIGGER_BPS:
            log.info(
                "Change %.0fbps < %dbps threshold — "
                "no commentary required",
                abs(change_bps), TRIGGER_BPS,
            )
            return None

        prompt = self._build_prompt(prior, current, change_bps)
        response = self._model.generate_content(prompt)
        draft = (
            f"AI-ASSISTED DRAFT — CFO REVIEW REQUIRED\n\n"
            f"{response.text}\n\n"
            f"[Generated by {self._model_id} | "
            f"CRR3 Art. 429 | C 47.00]"
        )
        log.info(
            "Leverage commentary generated: %+.0fbps "
            "Q%s→Q%s",
            change_bps,
            prior.quarter_end,
            current.quarter_end,
        )
        return LeverageCommentary(
            current_quarter=str(current.quarter_end),
            prior_ratio_pct=prior.leverage_ratio_pct,
            current_ratio_pct=current.leverage_ratio_pct,
            change_bps=change_bps,
            commentary_text=draft,
        )

    def _build_prompt(
        self,
        prior: LeverageRatioResult,
        current: LeverageRatioResult,
        change_bps: float,
    ) -> str:
        on_bs_chg = float(
            current.on_balance_sheet_gbp
            - prior.on_balance_sheet_gbp
        ) / 1e9
        saccr_chg = float(
            current.sa_ccr_derivatives_gbp
            - prior.sa_ccr_derivatives_gbp
        ) / 1e9
        direction = "increased" if change_bps > 0 else "decreased"
        return f"""Write a 250-word CFO-ready board commentary
on AWB's leverage ratio movement.

Prior quarter: {prior.leverage_ratio_pct:.2f}%
Current quarter: {current.leverage_ratio_pct:.2f}%
Movement: {change_bps:+.0f} basis points ({direction})
Minimum requirement: {current.MINIMUM_RATIO_PCT}% (CRR3 Art. 429)

Component drivers:
- On-balance-sheet: {on_bs_chg:+.2f}B change
- SA-CCR derivatives: {saccr_chg:+.2f}B change
- Total exposure: £{float(current.total_exposure_gbp)/1e9:.1f}B

Requirements:
- Explain magnitude and direction (a)
- Identify primary drivers from the 4 components (b)
- Comment on plan vs actual (c)
- Regulatory headroom commentary (d)
- British English, professional tone
- Suitable for AWB Board Risk Committee"""
